{
    "name": "Stock Voucher",
    "version": "19.0.0.0.0",
    "category": "Warehouse Management",
    "sequence": 14,
    "summary": "",
    "author": "ADHOC SA",
    "website": "www.adhoc.com.ar",
    "license": "AGPL-3",
    "images": [],
    "depends": [
        "sale_stock",
        "stock_ux",
    ],
    "data": [
        "security/stock_voucher_security.xml",
        "security/ir.model.access.csv",
        "wizards/stock_print_stock_voucher_views.xml",
        "wizards/stock_picking_wizard_views.xml",
        "views/stock_book_views.xml",
        "views/stock_picking_voucher_views.xml",
        "views/stock_picking_type_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_move_views.xml",
        "views/sale_order_views.xml",
        "data/ir_sequence_data.xml",
        "data/stock_book_data.xml",
        "report/stock_report_views.xml",
        "report/ir.action.reports.xml",
        "report/picking_templates.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": False,
}
